server:
  port: 9296

spring:
  profiles:    active: native
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/piyush-singh07/config-server
          clone-on-start: true